[context.production]
    command = "npm run build"
    publish = "build/"
    environment = { NODE_VERSION = "18" }

[context.deploy-preview]
    command = "npm run build"
    publish = "build/"
    environment = { NODE_VERSION = "19" }

[context.branch-deploy]
    publish = "."

[[redirects]]
    from = "/vpci"
    to = "https://vpci.picafe.dev/"
    status = 301
    force = true
    conditions = {Country = ["CA"]}